### =======================================
### MILESTONE 2: GROUP MANAGEMENT
### =======================================

### 14. Create a new Group (as Admin)
# @name createGroup
POST http://localhost:8080/api/v1/groups
Content-Type: application/json
Authorization: Bearer {{admin_jwt}}

{
  "name": "Java IPT - Fall 2025",
  "description": "The cohort for the Industrial Practical Training."
}

> {%
    client.global.set("groupId", response.body.id);
%}


### 15. Get the Attendee's User ID from the database
### Go to phpMyAdmin, look in the `users` table for 'attendee1@example.com'

# and copy its `id` value. Paste it into the `userId` variable below.
@attendeeId = 5112a634-ff38-4bbc-8f57-221007719534



### 16. Add Attendee as a Member to the Group
POST http://localhost:8080/api/v1/groups/{{groupId}}/members
Content-Type: application/json
Authorization: Bearer {{admin_jwt}}

{
  "userId": "{{attendeeId}}"
}


### 17. Get Group Details (should include the new member)
GET http://localhost:8080/api/v1/groups/{{groupId}}
Authorization: Bearer {{admin_jwt}}


### 18. Remove Member from the Group
DELETE http://localhost:8080/api/v1/groups/{{groupId}}/members/{{attendeeId}}
Authorization: Bearer {{admin_jwt}}


### 19. Get Group Details Again (member should be gone)
GET http://localhost:8080/api/v1/groups/{{groupId}}
Authorization: Bearer {{admin_jwt}}


### 20. Delete the Group
DELETE http://localhost:8080/api/v1/groups/{{groupId}}
Authorization: Bearer {{admin_jwt}}